apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - env:
          - name: httpport
            valueFrom:
              configMapKeyRef:
                key: httpport
                name: myenv
        image: imavei/httpserver:0.0.1
        imagePullPolicy: IfNotPresent
        name: httpserver
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 5   
          periodSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: "200Mi"
          requests:
            cpu: 200m
            memory: "100Mi"
        terminationMessagePath: /tmp/termination-log          
        terminationMessagePolicy: File
      volumes:
        - name: config
          configMap:
            name: myenv
      nodeSelector:
        app: httpserver


